leftnav:
- identifier: fc1f0afc-b4e2-4582-8cd8-d10de04113de
  name: RL
  pageRef: /lists/rl-1
  weight: 10
- identifier: 72369228-c03d-40e8-a728-ed3a366a16ea
  name: ER OCW with warning
  weight: 20
- identifier: 834bc6fa-1b21-44ce-bc58-afdd50f10237
  name: ER Mitopen
  weight: 30
- identifier: d07bf656-3013-426d-b052-fe2e162d8a1b
  name: ER external
  weight: 40
- identifier: 518ea479-4302-4115-9180-44ad21b36081
  name: ER OCW
  weight: 50
- identifier: 7a02eb19-f6f3-4d66-a2ce-a076aacf212a
  name: markdown test
  pageRef: /pages/markdown-test
  weight: 60
- identifier: 0dfa23a2-8da3-41a9-a925-a7bfcca9fda0
  name: Videos
  pageRef: /pages/videos
  weight: 70
- identifier: d695fd99-52d9-4d68-9b0a-4685d75e9098
  name: p1
  pageRef: /pages/p55
  weight: 80
